---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - auth
  - authentik
  - cloudflare-ddns
  - external-dns
  - ingress-nginx
  - metallb
  - k8s-gateway
