---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redacted-streams
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: nginx-php
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    persistence:
      data:
        enabled: true
        accessMode: ReadWriteOnce
        retain: true
        size: 1Gi
    podSecurityContext:
      fsGroup: 65534
      runAsGroup: 65534
      runAsUser: 65534
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns/is-public: "true"
        hosts:
          - host: redacted.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - redacted.${SECRET_DOMAIN}
            secretName: redacted-tls
