apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: authentik
    namespace: networking
spec:
    interval: 15m
    chart:
        spec:
            chart: authentik
            version: 2022.8.3
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: flux-system
            interval: 15m
    install:
        createNamespace: true
        remediation:
            retries: 5
    upgrade:
        remediation:
            retries: 5
    values:
        authentik:
            secret_key: ENC[AES256_GCM,data:kfVF4nJfqCrekoonCeIPyzab7/dNSSMLjJRGsObnEksfWNOY/ynDbjMGXCVJjsyYk/M=,iv:cJBoEQ6x85fxk0CgZZfGlngYkjYR1gG2SFCeyJ+dzLA=,tag:Y2umTVG3pCpi4HELbhgkeA==,type:str]
            error_reporting:
                enabled: true
            postgresql:
                password: ENC[AES256_GCM,data:u1pqbtMS58zs+bhgrraoYw==,iv:DylclQXA93lGUcRi6D65ZcKVAWahgx56CrfmjtZ76gk=,tag:hoVlsVfJMB430LajrtQu/g==,type:str]
        ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt-production
                external-dns/is-public: "true"
                external-dns.alpha.kubernetes.io/target: ipv4.${SECRET_DOMAIN}
            hosts:
                - host: authentik.${SECRET_DOMAIN}
                  paths:
                    - path: /
                      pathType: Prefix
            tls:
                - hosts:
                    - authentik.${SECRET_DOMAIN}
                  secretName: authentik-tls
        postgresql:
            enabled: true
            postgresqlPassword: ENC[AES256_GCM,data:QJ1O0vsAP3fxlobbMjVyNw==,iv:z6yZFyFbcY2PVxUsf0mADT1Z9hSvfaBppLU6vY9dx58=,tag:O7DQmsW4In6srQ7trT61Kw==,type:str]
        redis:
            enabled: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ths8xeh3s069gre6lfc845ksavkdpk2u2usqldux00ta80qugpsx8v8jf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaXFWcGZXRy8rRC94aFha
            R0JnZnpIeFlFUGJwMGFqRi82dTRCMk9CeXlRCi9TblhXRUlkNjlwYkVGSUFUOWRH
            Yk5aallZRFpBakp2Q2xscyt6SnBqWkEKLS0tIGdxbExGOWR3Tktzb0E4eGRGUjhE
            eVpnWEJNUGlIWVFQNStQSjhkRmp0VlEKc9IjrhRl+y5hjW7hpdn70PGl6LJiwARq
            b9KsvrCQLEiRNVL985FYZfNG/AjZfIJGdvLMCWl7j6FmrKQIQegXbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-24T03:45:07Z"
    mac: ENC[AES256_GCM,data:DSyGSHu7t5N6cu7bkT66i9gwPC7hnEbwXHn1R47B0tP5SdKKBUTCD8Ugi4JAeXwe6LJ39rhm/aPvS2HckGHzOydmgV7SWbbvxegvVzStGZcztbjQxvp3Q9z4Yt6O38DTLzzYaoGhIkatNqMYLWUpTi3hGNetWXvUaz0FDUiQ9qc=,iv:u0JU5vTI7GhpYNqPvvl0lJQP8PzqRfzFR4CpWLxVXcI=,tag:1gTP6useJ10zLfrKLgu9tQ==,type:str]
    pgp: []
    encrypted_regex: postgresqlPassword|password|secret_key
    version: 3.7.3
