---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-rbd
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: ceph-csi-rbd
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-ceph-csi-rbd
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    csiConfig:
      - clusterID: milomon
        monitors:
          - "192.168.0.91"
          - "192.168.0.92"
          - "192.168.0.93"
    storageClass:
      # Specifies whether the storageclass should be created
      create: true
      clusterID: milomon
